apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/dummy-watcher-info

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo-dev
