apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
