###############################
# dev
##############################
apiVersion: v1
kind: Namespace
metadata:
  name: argo-dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-dev
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-dev
  project: default
  source:
    path: environments/dev
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
