---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-prod
---
###############################
# childchain
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-childchain-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-prod
  project: default
  source:
    path: charts/dummy-childchain
    # helm:
    #   values: |
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: f94a77e
  # Disable auto sync
  # syncPolicy:
  #   automated: {}
---
###############################
# watcher
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-prod
  project: default
  source:
    path: charts/dummy-watcher
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: f94a77e
  syncPolicy:
    automated: {}
---
###############################
# watcher-info
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-prod
  project: default
  source:
    path: charts/dummy-watcher-info
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: f94a77e
  syncPolicy:
    automated: {}
