---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher-info
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-childchain-prod
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-childchain
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
