### ArgoCD
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: 8510c15438d756ac8491416a7700aaf96c151726

### Applications
env: prod
plasma_contracts_sha: a69c763
ethereum_network: rinkeby
