apiVersion: v1
kind: Namespace
metadata:
  name: argo-integration
---
###############################
# childchain
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-childchain-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration
  project: default
  source:
    path: charts/dummy-childchain
    # helm:
    #   values: |
    repoURL: https://github.com/boolafish/dummy-childchain-chart.git
    targetRevision: fc4ae7b33562e070661d68f38df3e2dcbd2c119e
    # Disable auto sync
    # syncPolicy:
    #   automated: {}
---
###############################
# watcher
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration
  project: default
  source:
    path: charts/dummy-watcher
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: f94a77e
  syncPolicy:
    automated: {}
---
###############################
# watcher-info
##############################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration
  project: default
  source:
    path: charts/dummy-watcher-info
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: f94a77e
  syncPolicy:
    automated: {}
