apiVersion: v1
kind: Namespace
metadata:
  name: argo-integration

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher
    helm:
      valueFiles:
        - values-integration.yaml
      values:
        replicas: 5

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher-info
    helm:
      valueFiles:
        - values-integration.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-childchain-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-childchain
    helm:
      valueFiles:
        - values-integration.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration
