apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-integration
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-integration
  project: default
  source:
    path: charts/dummy-watcher
    repoURL: https://github.com/boolafish/dummy-watcher-chart.git
    targetRevision: 044d4a280a71ce84
  syncPolicy:
    automated: {}
