---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-dev
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-dev

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-info-dev
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-watcher-info
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-dev

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-childchain-dev
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/arthurk/argocd-test.git
    targetRevision: HEAD
    path: charts/dummy-childchain
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-dev
