---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-watcher-dev
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-dev
  project: default
  source:
    path: charts/dummy-watcher
    repoURL: https://github.com/boolafish/dummy-watcher-chart.git
    targetRevision: 6f25a46d80f5a2cf3d91fad8d00a76359acb8728
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
